### PR TITLE
LastUpdate

### PR DESCRIPTION
**Pull request by jojedev**
Lets see if it works

### CODE REVIEW

**Comment by kasumi-1** [comment]
i made repo public so future pr should autobuild w/ vercel, did tiny commit to trigger :)

**Comment by kasumi-1** [comment]
Hi! I tried to fix a few issues with build. There is still one big one with ipfs plugin not being compatible with app dir, this issue reference it:

https://github.com/serverless-nextjs/serverless-next.js/issues/2480

**Comment by kasumi-1** [comment]
Also:

 ⨯ useSearchParams() should be wrapped in a suspense boundary at page "/dashboard/post-job". Read more: https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout
Error occurred prerendering page "/dashboard/post-job". Read more: https://nextjs.org/docs/messages/prerender-error

   Generating static pages (11/15) 
 ⨯ useSearchParams() should be wrapped in a suspense boundary at page "/new-post-job". Read more: https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout


You can test locally by running `yarn build` which should complete without any errors :)

**Comment by jojedev** [comment]
So it seems that ipfs-http-client has been [deprecared](https://github.com/ipfs/js-ipfs/issues/4336) in favour of [Helia](https://www.npmjs.com/package/helia). I'm moving forward to replace it, that should fix this issue.

Thanks for your support! @kasumi-1 


> Hi! I tried to fix a few issues with build. There is still one big one with ipfs plugin not being compatible with app dir, this issue reference it:
> 
> [serverless-nextjs/serverless-next.js#2480](https://github.com/serverless-nextjs/serverless-next.js/issues/2480)

**Pull request merged**
